export interface Hotel {
  id: string;
  name: string;
  city: string;
  country: string;
  region: string;
  category: string;
  type: string;
  rooms: number;
  pms: string;
  website: string;
  hasLoyalty: boolean;
  annualRevenue: string;
  tripAdvisorRating: number;
  bookingRating: number;
  icpScore: number;
  contactValue: number;
  status: "new" | "in_cadence" | "nurturing" | "sql" | "hibernated" | "disqualified";
  lastContact: string;
  decisionMaker: {
    name: string;
    title: string;
    initials: string;
    email: string;
    linkedIn: string;
    emailVerified: boolean;
    confirmed: boolean;
    yearsInRole: number;
  };
  cadence?: string;
  cadenceStep?: number;
  cadenceTotalSteps?: number;
  companyScore: number;
  personScore: number;
  behaviorScore: number;
  aiBriefing: string;
}

export interface CadenceStep {
  day: number;
  type: "email" | "linkedin" | "whatsapp" | "task" | "hibernate";
  description: string;
  sent?: number;
  opened?: number;
  replied?: number;
  conditionYes?: string;
  conditionNo?: string;
  conditionField?: string;
}

export interface Cadence {
  id: string;
  name: string;
  status: "active" | "paused" | "draft";
  leadsCount: number;
  responseRate: number;
  steps: CadenceStep[];
}

export interface Conversation {
  id: string;
  contactName: string;
  hotelName: string;
  hotelId: string;
  channel: "email" | "linkedin" | "whatsapp";
  priority: "urgent" | "normal" | "low";
  preview: string;
  contactValue: number;
  timeAgo: string;
  unread: boolean;
  requiresAction: boolean;
  messages: {
    from: string;
    content: string;
    timestamp: string;
    isOutbound: boolean;
  }[];
  suggestedReply?: string;
}

export interface ActivityItem {
  id: string;
  icon: string;
  description: string;
  timestamp: string;
  type: "email" | "linkedin" | "enrichment" | "sql" | "cadence";
}

export const hotels: Hotel[] = [
  {
    id: "1",
    name: "Hotel Arts Barcelona",
    city: "Barcelona",
    country: "Spain",
    region: "Catalonia",
    category: "5",
    type: "Urban",
    rooms: 483,
    pms: "Opera",
    website: "hotelartsbarcelona.com",
    hasLoyalty: true,
    annualRevenue: "45M",
    tripAdvisorRating: 4.6,
    bookingRating: 9.1,
    icpScore: 72,
    contactValue: 28,
    status: "in_cadence",
    lastContact: "2026-02-17",
    decisionMaker: {
      name: "Elena Martínez",
      title: "Directora de Revenue",
      initials: "EM",
      email: "e.m***@hotelar***.com",
      linkedIn: "linkedin.com/in/elenamartinez",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 5,
    },
    cadence: "Spain Boutique 4-5★",
    cadenceStep: 3,
    cadenceTotalSteps: 8,
    companyScore: 28,
    personScore: 10,
    behaviorScore: 0,
    aiBriefing: "Hotel de lujo 5★ en Barcelona con 483 habitaciones. Utiliza Opera como PMS y ya cuenta con un programa de fidelización propio. A pesar de esto, las reviews en TripAdvisor mencionan inconsistencias en el reconocimiento de huéspedes recurrentes — oportunidad para módulo de loyalty avanzado. La directora de revenue lleva 5+ años en el cargo.",
  },
  {
    id: "2",
    name: "Boutique Can Mostatxins",
    city: "Palma de Mallorca",
    country: "Spain",
    region: "Balearic Islands",
    category: "4",
    type: "Boutique",
    rooms: 72,
    pms: "Mews",
    website: "canmostatxins.com",
    hasLoyalty: false,
    annualRevenue: "3.2M",
    tripAdvisorRating: 4.8,
    bookingRating: 9.4,
    icpScore: 91,
    contactValue: 34,
    status: "in_cadence",
    lastContact: "2026-02-18",
    decisionMaker: {
      name: "Marc Puig",
      title: "Director General",
      initials: "MP",
      email: "m.p***@canmos***.com",
      linkedIn: "linkedin.com/in/marcpuig",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 3,
    },
    cadence: "Spain Boutique 4-5★",
    cadenceStep: 3,
    cadenceTotalSteps: 8,
    companyScore: 32,
    personScore: 12,
    behaviorScore: 2,
    aiBriefing: "Hotel boutique 4★ en Palma con 72 habitaciones. Actualmente usa Mews como PMS pero no tiene programa de fidelización activo. Las reviews en TripAdvisor mencionan alta satisfacción de huéspedes pero baja tasa de visitas recurrentes — pain point directo para el módulo de loyalty de Fideltour. El director lleva 3+ años en el cargo indicando estabilidad. Cadencia recomendada: Spain Boutique 4-5★.",
  },
  {
    id: "3",
    name: "Hotel Mercer Barcelona",
    city: "Barcelona",
    country: "Spain",
    region: "Catalonia",
    category: "5",
    type: "Boutique",
    rooms: 28,
    pms: "Cloudbeds",
    website: "mercerbarcelona.com",
    hasLoyalty: false,
    annualRevenue: "4.1M",
    tripAdvisorRating: 4.9,
    bookingRating: 9.6,
    icpScore: 94,
    contactValue: 48,
    status: "nurturing",
    lastContact: "2026-02-15",
    decisionMaker: {
      name: "Isabel Torres",
      title: "Directora Comercial",
      initials: "IT",
      email: "i.t***@mercer***.com",
      linkedIn: "linkedin.com/in/isabeltorres",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 4,
    },
    cadence: "Spain Boutique 4-5★",
    cadenceStep: 6,
    cadenceTotalSteps: 8,
    companyScore: 36,
    personScore: 18,
    behaviorScore: 8,
    aiBriefing: "Boutique hotel de lujo 5★ en el Barrio Gótico con solo 28 habitaciones. Usa Cloudbeds como PMS, sin programa de loyalty. Altísima valoración en plataformas (9.6 Booking). El tamaño reducido lo hace ideal para implementación ágil de Fideltour. Contact Value cercano a SQL threshold.",
  },
  {
    id: "4",
    name: "Only YOU Hotel Sevilla",
    city: "Sevilla",
    country: "Spain",
    region: "Andalusia",
    category: "4",
    type: "Boutique",
    rooms: 93,
    pms: "Protel",
    website: "onlyyouhotels.com",
    hasLoyalty: false,
    annualRevenue: "5.8M",
    tripAdvisorRating: 4.5,
    bookingRating: 8.9,
    icpScore: 85,
    contactValue: 22,
    status: "in_cadence",
    lastContact: "2026-02-16",
    decisionMaker: {
      name: "Ana García",
      title: "Revenue Manager",
      initials: "AG",
      email: "a.g***@onlyy***.com",
      linkedIn: "linkedin.com/in/anagarcia",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 2,
    },
    cadence: "Spain Boutique 4-5★",
    cadenceStep: 2,
    cadenceTotalSteps: 8,
    companyScore: 30,
    personScore: 8,
    behaviorScore: 2,
    aiBriefing: "Hotel lifestyle 4★ en Sevilla con 93 habitaciones. PMS Protel sin programa de loyalty. Parte de la marca Only YOU con expansión activa. Oportunidad de captar la cadena completa si se cierra este hotel como piloto.",
  },
  {
    id: "5",
    name: "Gran Hotel La Perla",
    city: "Pamplona",
    country: "Spain",
    region: "Navarra",
    category: "5",
    type: "Urban",
    rooms: 44,
    pms: "Sihot",
    website: "granhotellaperla.com",
    hasLoyalty: false,
    annualRevenue: "3.5M",
    tripAdvisorRating: 4.7,
    bookingRating: 9.2,
    icpScore: 88,
    contactValue: 52,
    status: "sql",
    lastContact: "2026-02-19",
    decisionMaker: {
      name: "Javier Echeverría",
      title: "Director General",
      initials: "JE",
      email: "j.e***@granho***.com",
      linkedIn: "linkedin.com/in/javierecheverria",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 7,
    },
    companyScore: 34,
    personScore: 22,
    behaviorScore: 18,
    aiBriefing: "Hotel histórico 5★ en Pamplona con 44 habitaciones. Sin loyalty y con PMS legacy (Sihot). Director con 7+ años muy estable. Ya ha mostrado interés activo — Contact Value > 50, clasificado como SQL.",
  },
  {
    id: "6",
    name: "Hotel Neri Barcelona",
    city: "Barcelona",
    country: "Spain",
    region: "Catalonia",
    category: "5",
    type: "Boutique",
    rooms: 22,
    pms: "Mews",
    website: "hotelneri.com",
    hasLoyalty: false,
    annualRevenue: "2.8M",
    tripAdvisorRating: 4.7,
    bookingRating: 9.3,
    icpScore: 90,
    contactValue: 15,
    status: "new",
    lastContact: "",
    decisionMaker: {
      name: "Carla Vidal",
      title: "General Manager",
      initials: "CV",
      email: "c.v***@hotel***.com",
      linkedIn: "linkedin.com/in/carlavidal",
      emailVerified: false,
      confirmed: false,
      yearsInRole: 1,
    },
    companyScore: 35,
    personScore: 5,
    behaviorScore: 0,
    aiBriefing: "Boutique de lujo 5★ en Barcelona Gótico con solo 22 habitaciones. Usa Mews, sin loyalty. Muy bien valorado. Lead nuevo aún sin contactar.",
  },
  {
    id: "7",
    name: "Hotel Casa Dann Carlton",
    city: "Bogotá",
    country: "Colombia",
    region: "Bogotá D.C.",
    category: "5",
    type: "Urban",
    rooms: 268,
    pms: "Opera",
    website: "casadanncarlton.com",
    hasLoyalty: true,
    annualRevenue: "12M",
    tripAdvisorRating: 4.3,
    bookingRating: 8.5,
    icpScore: 65,
    contactValue: 18,
    status: "in_cadence",
    lastContact: "2026-02-14",
    decisionMaker: {
      name: "Carlos Méndez",
      title: "Director Comercial",
      initials: "CM",
      email: "c.m***@casad***.com",
      linkedIn: "linkedin.com/in/carlosmendez",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 4,
    },
    cadence: "LATAM Independent Hotels",
    cadenceStep: 4,
    cadenceTotalSteps: 7,
    companyScore: 24,
    personScore: 10,
    behaviorScore: 2,
    aiBriefing: "Hotel 5★ en Bogotá con 268 habitaciones. Usa Opera y tiene programa de loyalty básico que podría mejorarse. Mercado colombiano en crecimiento para Fideltour.",
  },
  {
    id: "8",
    name: "Presidente InterContinental CDMX",
    city: "Ciudad de México",
    country: "Mexico",
    region: "CDMX",
    category: "5",
    type: "Urban",
    rooms: 659,
    pms: "Opera",
    website: "intercontinental.com/mexico",
    hasLoyalty: true,
    annualRevenue: "38M",
    tripAdvisorRating: 4.4,
    bookingRating: 8.7,
    icpScore: 55,
    contactValue: 12,
    status: "in_cadence",
    lastContact: "2026-02-12",
    decisionMaker: {
      name: "Roberto Hernández",
      title: "VP Revenue Management",
      initials: "RH",
      email: "r.h***@inter***.com",
      linkedIn: "linkedin.com/in/robertohernandez",
      emailVerified: true,
      confirmed: false,
      yearsInRole: 6,
    },
    cadence: "LATAM Independent Hotels",
    cadenceStep: 2,
    cadenceTotalSteps: 7,
    companyScore: 20,
    personScore: 8,
    behaviorScore: 0,
    aiBriefing: "Mega hotel 5★ en CDMX con 659 habitaciones. Opera PMS con loyalty de cadena. ICP medio — hotel de cadena grande puede ser más difícil de cerrar pero alto volumen potencial.",
  },
  {
    id: "9",
    name: "Miraflores Park Hotel",
    city: "Lima",
    country: "Peru",
    region: "Lima",
    category: "5",
    type: "Urban",
    rooms: 81,
    pms: "Cloudbeds",
    website: "miraflorespark.com",
    hasLoyalty: false,
    annualRevenue: "6.2M",
    tripAdvisorRating: 4.6,
    bookingRating: 9.0,
    icpScore: 82,
    contactValue: 8,
    status: "new",
    lastContact: "",
    decisionMaker: {
      name: "Roberto Kim",
      title: "Gerente General",
      initials: "RK",
      email: "r.k***@miraf***.com",
      linkedIn: "linkedin.com/in/robertokim",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 3,
    },
    companyScore: 30,
    personScore: 6,
    behaviorScore: 0,
    aiBriefing: "Hotel 5★ en Miraflores, Lima con 81 habitaciones. Cloudbeds como PMS, sin loyalty. Excelentes ratings. Lead nuevo con buen ICP score.",
  },
  {
    id: "10",
    name: "Hotel Boutique Casa de Campo",
    city: "Cartagena",
    country: "Colombia",
    region: "Bolívar",
    category: "4",
    type: "Boutique",
    rooms: 35,
    pms: "Little Hotelier",
    website: "casadecampohotel.co",
    hasLoyalty: false,
    annualRevenue: "1.8M",
    tripAdvisorRating: 4.8,
    bookingRating: 9.5,
    icpScore: 87,
    contactValue: 28,
    status: "nurturing",
    lastContact: "2026-02-13",
    decisionMaker: {
      name: "Laura Vega",
      title: "Directora de Operaciones",
      initials: "LV",
      email: "l.v***@casad***.co",
      linkedIn: "linkedin.com/in/lauravega",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 2,
    },
    cadence: "LATAM Independent Hotels",
    cadenceStep: 5,
    cadenceTotalSteps: 7,
    companyScore: 32,
    personScore: 14,
    behaviorScore: 4,
    aiBriefing: "Boutique 4★ en Cartagena con 35 habitaciones. Little Hotelier como PMS — migración potencial. Sin loyalty. Altas valoraciones. En nurturing con buen engagement.",
  },
  {
    id: "11",
    name: "Hotel Xcaret Arte",
    city: "Playa del Carmen",
    country: "Mexico",
    region: "Quintana Roo",
    category: "5",
    type: "Resort",
    rooms: 900,
    pms: "Opera",
    website: "hotelxcaretarte.com",
    hasLoyalty: true,
    annualRevenue: "85M",
    tripAdvisorRating: 4.9,
    bookingRating: 9.7,
    icpScore: 45,
    contactValue: 5,
    status: "new",
    lastContact: "",
    decisionMaker: {
      name: "Patricia Lozano",
      title: "VP Comercial",
      initials: "PL",
      email: "p.l***@xcaret***.com",
      linkedIn: "linkedin.com/in/patricialozano",
      emailVerified: false,
      confirmed: false,
      yearsInRole: 8,
    },
    companyScore: 15,
    personScore: 5,
    behaviorScore: 0,
    aiBriefing: "Mega resort all-inclusive en Riviera Maya con 900 habitaciones. Gran escala pero ICP bajo para Fideltour — modelo all-inclusive difiere del target principal.",
  },
  {
    id: "12",
    name: "Hotel Panamá Canal",
    city: "Ciudad de Panamá",
    country: "Panama",
    region: "Panamá",
    category: "4",
    type: "Urban",
    rooms: 120,
    pms: "Protel",
    website: "hotelpanamcanal.com",
    hasLoyalty: false,
    annualRevenue: "4.5M",
    tripAdvisorRating: 4.2,
    bookingRating: 8.3,
    icpScore: 76,
    contactValue: 20,
    status: "in_cadence",
    lastContact: "2026-02-10",
    decisionMaker: {
      name: "Miguel Arias",
      title: "Director General",
      initials: "MA",
      email: "m.a***@hotel***.com",
      linkedIn: "linkedin.com/in/miguelarias",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 5,
    },
    cadence: "LATAM Independent Hotels",
    cadenceStep: 3,
    cadenceTotalSteps: 7,
    companyScore: 26,
    personScore: 10,
    behaviorScore: 4,
    aiBriefing: "Hotel 4★ en Ciudad de Panamá con 120 habitaciones. Sin loyalty, Protel PMS. Buen fit para Fideltour en mercado panameño emergente.",
  },
  {
    id: "13",
    name: "Hotel Villa Real Madrid",
    city: "Madrid",
    country: "Spain",
    region: "Madrid",
    category: "5",
    type: "Urban",
    rooms: 115,
    pms: "Sihot",
    website: "hotelvillareal.com",
    hasLoyalty: false,
    annualRevenue: "8.2M",
    tripAdvisorRating: 4.5,
    bookingRating: 8.8,
    icpScore: 83,
    contactValue: 42,
    status: "nurturing",
    lastContact: "2026-02-17",
    decisionMaker: {
      name: "Fernando López",
      title: "Director de Ventas",
      initials: "FL",
      email: "f.l***@villa***.com",
      linkedIn: "linkedin.com/in/fernandolopez",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 4,
    },
    cadence: "Spain Boutique 4-5★",
    cadenceStep: 7,
    cadenceTotalSteps: 8,
    companyScore: 30,
    personScore: 16,
    behaviorScore: 10,
    aiBriefing: "Hotel 5★ en Madrid con 115 habitaciones. Sin loyalty, Sihot PMS. CV alto (42), cerca de SQL. Avanzado en cadencia de nurturing.",
  },
  {
    id: "14",
    name: "Finca Cortesin Resort",
    city: "Málaga",
    country: "Spain",
    region: "Andalusia",
    category: "GL",
    type: "Resort",
    rooms: 67,
    pms: "Protel",
    website: "fincacortesin.com",
    hasLoyalty: false,
    annualRevenue: "15M",
    tripAdvisorRating: 4.9,
    bookingRating: 9.5,
    icpScore: 92,
    contactValue: 55,
    status: "sql",
    lastContact: "2026-02-19",
    decisionMaker: {
      name: "María Sánchez",
      title: "Directora General",
      initials: "MS",
      email: "m.s***@finca***.com",
      linkedIn: "linkedin.com/in/mariasanchez",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 6,
    },
    companyScore: 38,
    personScore: 24,
    behaviorScore: 20,
    aiBriefing: "Resort GL en Málaga con 67 habitaciones. Protel PMS, sin loyalty. Uno de los mejores resorts de España. SQL activo con alto engagement.",
  },
  {
    id: "15",
    name: "Hotel Rural Can Cuch",
    city: "Montseny",
    country: "Spain",
    region: "Catalonia",
    category: "4",
    type: "Rural",
    rooms: 18,
    pms: "Cloudbeds",
    website: "cancuch.com",
    hasLoyalty: false,
    annualRevenue: "0.9M",
    tripAdvisorRating: 4.6,
    bookingRating: 9.1,
    icpScore: 68,
    contactValue: 10,
    status: "hibernated",
    lastContact: "2025-12-05",
    decisionMaker: {
      name: "Jordi Mas",
      title: "Propietario",
      initials: "JM",
      email: "j.m***@cancu***.com",
      linkedIn: "linkedin.com/in/jordimas",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 10,
    },
    companyScore: 22,
    personScore: 8,
    behaviorScore: 0,
    aiBriefing: "Hotel rural 4★ en Montseny con 18 habitaciones. Pequeño pero con buen ICP. Hibernado tras no responder a cadencia anterior. Considerar reactivación en Q2.",
  },
  {
    id: "16",
    name: "Hospes Palau de la Mar",
    city: "Valencia",
    country: "Spain",
    region: "Valencia",
    category: "5",
    type: "Boutique",
    rooms: 66,
    pms: "Mews",
    website: "hospes.com/valencia",
    hasLoyalty: false,
    annualRevenue: "4.8M",
    tripAdvisorRating: 4.5,
    bookingRating: 9.0,
    icpScore: 86,
    contactValue: 30,
    status: "in_cadence",
    lastContact: "2026-02-16",
    decisionMaker: {
      name: "Pablo Ruiz",
      title: "Director de Hotel",
      initials: "PR",
      email: "p.r***@hospe***.com",
      linkedIn: "linkedin.com/in/pabloruiz",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 3,
    },
    cadence: "Spain Boutique 4-5★",
    cadenceStep: 4,
    cadenceTotalSteps: 8,
    companyScore: 32,
    personScore: 14,
    behaviorScore: 6,
    aiBriefing: "Boutique 5★ en Valencia con 66 habitaciones. Mews PMS, sin loyalty. Parte de cadena Hospes — potencial de escalado. Buen engagement hasta ahora.",
  },
  {
    id: "17",
    name: "Hotel Bogotá Centro",
    city: "Bogotá",
    country: "Colombia",
    region: "Bogotá D.C.",
    category: "3",
    type: "Urban",
    rooms: 85,
    pms: "Little Hotelier",
    website: "hotelbogotacentro.com",
    hasLoyalty: false,
    annualRevenue: "1.5M",
    tripAdvisorRating: 3.9,
    bookingRating: 7.8,
    icpScore: 58,
    contactValue: 28,
    status: "in_cadence",
    lastContact: "2026-02-15",
    decisionMaker: {
      name: "Andrés Moreno",
      title: "Gerente",
      initials: "AM",
      email: "a.m***@hotel***.com",
      linkedIn: "linkedin.com/in/andresmoreno",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 2,
    },
    cadence: "LATAM Independent Hotels",
    cadenceStep: 3,
    cadenceTotalSteps: 7,
    companyScore: 18,
    personScore: 10,
    behaviorScore: 6,
    aiBriefing: "Hotel 3★ en centro de Bogotá con 85 habitaciones. ICP medio-bajo pero mostrando interés. Little Hotelier como PMS.",
  },
  {
    id: "18",
    name: "Hotel Cala de Mar Ixtapa",
    city: "Ixtapa",
    country: "Mexico",
    region: "Guerrero",
    category: "5",
    type: "Resort",
    rooms: 59,
    pms: "Cloudbeds",
    website: "calademarresort.com",
    hasLoyalty: false,
    annualRevenue: "7.8M",
    tripAdvisorRating: 4.7,
    bookingRating: 9.2,
    icpScore: 84,
    contactValue: 35,
    status: "nurturing",
    lastContact: "2026-02-14",
    decisionMaker: {
      name: "Daniela Fuentes",
      title: "Directora Comercial",
      initials: "DF",
      email: "d.f***@calad***.com",
      linkedIn: "linkedin.com/in/danielafuentes",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 3,
    },
    cadence: "LATAM Independent Hotels",
    cadenceStep: 6,
    cadenceTotalSteps: 7,
    companyScore: 32,
    personScore: 16,
    behaviorScore: 8,
    aiBriefing: "Resort boutique 5★ en Ixtapa con 59 habitaciones. Sin loyalty, Cloudbeds PMS. Excelente fit para Fideltour. Avanzado en cadencia.",
  },
  {
    id: "19",
    name: "Hotel Boutique Palma Suites",
    city: "Palma de Mallorca",
    country: "Spain",
    region: "Balearic Islands",
    category: "4",
    type: "Boutique",
    rooms: 24,
    pms: "Mews",
    website: "palmasuites.com",
    hasLoyalty: false,
    annualRevenue: "1.6M",
    tripAdvisorRating: 4.7,
    bookingRating: 9.3,
    icpScore: 89,
    contactValue: 22,
    status: "in_cadence",
    lastContact: "2026-02-18",
    decisionMaker: {
      name: "Catalina Fiol",
      title: "Propietaria",
      initials: "CF",
      email: "c.f***@palma***.com",
      linkedIn: "linkedin.com/in/catalinafiol",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 5,
    },
    cadence: "Spain Boutique 4-5★",
    cadenceStep: 2,
    cadenceTotalSteps: 8,
    companyScore: 34,
    personScore: 12,
    behaviorScore: 2,
    aiBriefing: "Boutique 4★ en Palma con 24 habitaciones. Mews PMS, sin loyalty. Propietaria directa — decisión rápida potencial.",
  },
  {
    id: "20",
    name: "Hotel Lima Miraflores Select",
    city: "Lima",
    country: "Peru",
    region: "Lima",
    category: "4",
    type: "Urban",
    rooms: 102,
    pms: "Protel",
    website: "limamirafloress.com",
    hasLoyalty: false,
    annualRevenue: "3.8M",
    tripAdvisorRating: 4.3,
    bookingRating: 8.6,
    icpScore: 74,
    contactValue: 12,
    status: "in_cadence",
    lastContact: "2026-02-11",
    decisionMaker: {
      name: "Santiago Reyes",
      title: "Director de Operaciones",
      initials: "SR",
      email: "s.r***@limam***.com",
      linkedIn: "linkedin.com/in/santiagoreyes",
      emailVerified: true,
      confirmed: true,
      yearsInRole: 2,
    },
    cadence: "LATAM Independent Hotels",
    cadenceStep: 2,
    cadenceTotalSteps: 7,
    companyScore: 26,
    personScore: 8,
    behaviorScore: 2,
    aiBriefing: "Hotel 4★ en Miraflores, Lima con 102 habitaciones. Protel PMS, sin loyalty. Mercado peruano con potencial de crecimiento para Fideltour.",
  },
];

export const cadences: Cadence[] = [
  {
    id: "1",
    name: "Spain Boutique 4-5★",
    status: "active",
    leadsCount: 142,
    responseRate: 18.3,
    steps: [
      { day: 1, type: "email", description: "Email #1 - Introducción personalizada", sent: 142, opened: 89, replied: 12, conditionField: "opened", conditionYes: "LinkedIn connection request", conditionNo: "Email #1B - Asunto alternativo (A/B)" },
      { day: 3, type: "linkedin", description: "LinkedIn - Solicitud de conexión", sent: 89, opened: 67, replied: 8 },
      { day: 6, type: "linkedin", description: "LinkedIn - Mensaje de seguimiento (si conectado)", sent: 67, opened: 45, replied: 6 },
      { day: 9, type: "email", description: "Email #2 - Pain point + recurso Academy", sent: 120, opened: 72, replied: 15, conditionField: "contactValue > 40", conditionYes: "Notificar SDR inmediatamente" },
      { day: 12, type: "whatsapp", description: "WhatsApp (si número disponible)", sent: 38, opened: 32, replied: 14 },
      { day: 18, type: "email", description: "Email #3 - Email de ruptura", sent: 95, opened: 41, replied: 5 },
      { day: 25, type: "hibernate", description: "Hibernar 60 días", sent: 60 },
    ],
  },
  {
    id: "2",
    name: "LATAM Independent Hotels",
    status: "active",
    leadsCount: 67,
    responseRate: 11.7,
    steps: [
      { day: 1, type: "email", description: "Email #1 - Intro mercado LATAM", sent: 67, opened: 38, replied: 5 },
      { day: 4, type: "linkedin", description: "LinkedIn - Conexión + nota personalizada", sent: 38, opened: 24, replied: 3 },
      { day: 8, type: "email", description: "Email #2 - Caso de éxito LATAM", sent: 55, opened: 30, replied: 7 },
      { day: 12, type: "whatsapp", description: "WhatsApp - Mensaje directo", sent: 22, opened: 18, replied: 8 },
      { day: 16, type: "email", description: "Email #3 - Oferta piloto gratuito", sent: 42, opened: 20, replied: 3 },
      { day: 22, type: "task", description: "Tarea: Revisión manual del lead", sent: 30 },
      { day: 30, type: "hibernate", description: "Hibernar 90 días", sent: 18 },
    ],
  },
  {
    id: "3",
    name: "Recycled Q4 2025",
    status: "paused",
    leadsCount: 23,
    responseRate: 8.1,
    steps: [
      { day: 1, type: "email", description: "Email #1 - Re-engagement", sent: 23, opened: 12, replied: 2 },
      { day: 5, type: "linkedin", description: "LinkedIn - Nuevo mensaje", sent: 12, opened: 8, replied: 1 },
      { day: 10, type: "email", description: "Email #2 - Nueva propuesta de valor", sent: 18, opened: 9, replied: 1 },
      { day: 15, type: "email", description: "Email #3 - Último intento", sent: 15, opened: 6, replied: 0 },
      { day: 20, type: "hibernate", description: "Descartar o hibernar", sent: 10 },
    ],
  },
  {
    id: "4",
    name: "Spain Small Chains",
    status: "draft",
    leadsCount: 0,
    responseRate: 0,
    steps: [
      { day: 1, type: "email", description: "Email #1 - Intro cadenas pequeñas" },
      { day: 4, type: "linkedin", description: "LinkedIn - Conexión con director" },
      { day: 8, type: "email", description: "Email #2 - ROI para cadenas" },
      { day: 12, type: "task", description: "Tarea: Llamada de descubrimiento" },
      { day: 18, type: "email", description: "Email #3 - Caso de éxito cadena" },
      { day: 24, type: "email", description: "Email #4 - Ruptura" },
    ],
  },
];

export const conversations: Conversation[] = [
  {
    id: "1",
    contactName: "Marc Puig",
    hotelName: "Boutique Can Mostatxins",
    hotelId: "2",
    channel: "email",
    priority: "urgent",
    preview: "Hola, me interesa saber más sobre vuestra solución de fidelización...",
    contactValue: 34,
    timeAgo: "Hace 2h",
    unread: true,
    requiresAction: true,
    messages: [
      { from: "Fideltour", content: "Hola Marc, espero que estés bien. Me pongo en contacto contigo porque he visto que Can Mostatxins tiene unas valoraciones excepcionales en Booking (9.4) pero no cuenta con un programa de fidelización propio. En Fideltour ayudamos a hoteles boutique como el tuyo a aumentar la tasa de retorno de huéspedes en un 23% de media. ¿Te interesaría una breve llamada de 15 min para explorar cómo podríamos ayudaros?", timestamp: "15 Feb 2026, 10:00", isOutbound: true },
      { from: "Marc Puig", content: "Hola, me interesa saber más sobre vuestra solución de fidelización. Efectivamente es algo que tenemos pendiente. ¿Podríais enviarme más información sobre los módulos y precios? También me gustaría entender cómo se integra con Mews que es nuestro PMS actual.", timestamp: "19 Feb 2026, 14:32", isOutbound: false },
    ],
    suggestedReply: "Hola Marc, muchas gracias por tu interés. Me alegra saber que la fidelización es una prioridad para Can Mostatxins. Te adjunto nuestra ficha de producto con los módulos disponibles y el detalle de precios para hoteles boutique de vuestro perfil.\n\nRespecto a Mews, tenemos una integración nativa certificada que permite sincronización en tiempo real de perfiles de huéspedes, historial de estancias y preferencias. La implementación típica tarda 2-3 semanas.\n\n¿Te parece bien si agendamos una demo de 20 min para la semana que viene? Así puedes ver la plataforma en acción con datos reales de un hotel similar al vuestro.",
  },
  {
    id: "2",
    contactName: "Ana García",
    hotelName: "Hotel Boutique Palma Suites",
    hotelId: "19",
    channel: "linkedin",
    priority: "urgent",
    preview: "Ha aceptado tu solicitud de conexión en LinkedIn",
    contactValue: 22,
    timeAgo: "Hace 4h",
    unread: true,
    requiresAction: true,
    messages: [
      { from: "Fideltour", content: "Hola Ana, soy SDR en Fideltour. He visto que Palma Suites tiene unas valoraciones excelentes y me encantaría conectar contigo para compartir cómo estamos ayudando a hoteles boutique en Baleares con la fidelización de huéspedes.", timestamp: "18 Feb 2026, 09:00", isOutbound: true },
      { from: "Ana García", content: "[Solicitud de conexión aceptada]", timestamp: "19 Feb 2026, 12:15", isOutbound: false },
    ],
    suggestedReply: "Hola Ana, muchas gracias por aceptar mi solicitud. Como te comentaba, en Fideltour trabajamos con varios hoteles boutique en Mallorca ayudándoles a convertir huéspedes ocasionales en clientes recurrentes.\n\n¿Te interesaría una breve charla de 10 min para ver si tiene sentido explorar una colaboración?",
  },
  {
    id: "3",
    contactName: "Carlos Méndez",
    hotelName: "Hotel Casa Dann Carlton",
    hotelId: "7",
    channel: "email",
    priority: "normal",
    preview: "Ahora mismo no es el mejor momento, pero podrían contactarme en Q2...",
    contactValue: 18,
    timeAgo: "Ayer",
    unread: false,
    requiresAction: false,
    messages: [
      { from: "Fideltour", content: "Hola Carlos, te escribo desde Fideltour. Hemos analizado el perfil de Hotel Casa Dann Carlton y creemos que hay una oportunidad interesante para mejorar la retención de huéspedes con nuestro módulo de loyalty...", timestamp: "14 Feb 2026, 11:00", isOutbound: true },
      { from: "Carlos Méndez", content: "Ahora mismo no es el mejor momento, pero podrían contactarme en Q2. Estamos en medio de una renovación y cualquier proyecto nuevo tendría que esperar a abril/mayo.", timestamp: "18 Feb 2026, 16:45", isOutbound: false },
    ],
    suggestedReply: "Hola Carlos, entiendo perfectamente. Las renovaciones requieren toda la atención. Agendaré un follow-up para principios de abril.\n\nMientras tanto, te dejo acceso a nuestra Academy donde encontrarás recursos sobre cómo otros hoteles en Colombia han implementado programas de loyalty exitosos. ¡Mucho éxito con la renovación!",
  },
  {
    id: "4",
    contactName: "Laura Vega",
    hotelName: "Hotel Boutique Casa de Campo",
    hotelId: "10",
    channel: "email",
    priority: "low",
    preview: "Email abierto (sin respuesta) - Email #2 Pain point",
    contactValue: 28,
    timeAgo: "Ayer",
    unread: false,
    requiresAction: false,
    messages: [
      { from: "Fideltour", content: "Hola Laura, quería compartir contigo un caso de éxito de un hotel boutique en Cartagena similar a Casa de Campo que logró aumentar su RevPAR un 18% implementando nuestro programa de loyalty...", timestamp: "17 Feb 2026, 10:00", isOutbound: true },
    ],
  },
  {
    id: "5",
    contactName: "Roberto Kim",
    hotelName: "Miraflores Park Hotel",
    hotelId: "9",
    channel: "email",
    priority: "low",
    preview: "Email #1 enviado - Introducción personalizada",
    contactValue: 12,
    timeAgo: "Hace 2 días",
    unread: false,
    requiresAction: false,
    messages: [
      { from: "Fideltour", content: "Hola Roberto, me pongo en contacto contigo desde Fideltour. He visto que Miraflores Park tiene unas valoraciones excepcionales pero aún no cuenta con un programa de fidelización...", timestamp: "17 Feb 2026, 09:00", isOutbound: true },
    ],
  },
  {
    id: "6",
    contactName: "Pablo Ruiz",
    hotelName: "Hospes Palau de la Mar",
    hotelId: "16",
    channel: "whatsapp",
    priority: "normal",
    preview: "Interesante propuesta. Déjame revisarlo con mi equipo...",
    contactValue: 30,
    timeAgo: "Hace 3 días",
    unread: false,
    requiresAction: false,
    messages: [
      { from: "Fideltour", content: "Hola Pablo, soy de Fideltour. Te envío por WhatsApp el enlace a nuestra demo interactiva para que puedas verla cuando te venga bien.", timestamp: "16 Feb 2026, 11:30", isOutbound: true },
      { from: "Pablo Ruiz", content: "Interesante propuesta. Déjame revisarlo con mi equipo y te respondo la semana que viene.", timestamp: "16 Feb 2026, 14:20", isOutbound: false },
    ],
  },
  {
    id: "7",
    contactName: "Fernando López",
    hotelName: "Hotel Villa Real Madrid",
    hotelId: "13",
    channel: "email",
    priority: "normal",
    preview: "¿Podríamos agendar una llamada para la próxima semana?",
    contactValue: 42,
    timeAgo: "Hace 2 días",
    unread: false,
    requiresAction: false,
    messages: [
      { from: "Fernando López", content: "¿Podríamos agendar una llamada para la próxima semana? Me interesa entender mejor cómo funciona la integración con Sihot y los costes de implementación.", timestamp: "17 Feb 2026, 09:30", isOutbound: false },
      { from: "Fideltour", content: "¡Por supuesto Fernando! Te envío mi calendario para que reserves el slot que mejor te convenga: [link]. La integración con Sihot es una de nuestras más maduras. Prepararé una demo personalizada.", timestamp: "17 Feb 2026, 10:15", isOutbound: true },
    ],
  },
];

export const recentActivity: ActivityItem[] = [
  { id: "1", icon: "email", description: "Marc Puig (Can Mostatxins) respondió al Email #2", timestamp: "Hace 2h", type: "email" },
  { id: "2", icon: "linkedin", description: "Ana García (Palma Suites) aceptó conexión LinkedIn", timestamp: "Hace 4h", type: "linkedin" },
  { id: "3", icon: "enrichment", description: "5 hoteles nuevos enriquecidos con datos de AI", timestamp: "Hace 6h", type: "enrichment" },
  { id: "4", icon: "sql", description: "Gran Hotel La Perla alcanzó SQL (CV: 52)", timestamp: "Ayer", type: "sql" },
  { id: "5", icon: "cadence", description: "Cadencia 'Spain Boutique' envió 45 emails programados", timestamp: "Ayer", type: "cadence" },
  { id: "6", icon: "email", description: "Fernando López (Villa Real) solicitó demo", timestamp: "Hace 2 días", type: "email" },
  { id: "7", icon: "enrichment", description: "12 emails verificados en lote de LATAM", timestamp: "Hace 2 días", type: "enrichment" },
  { id: "8", icon: "sql", description: "Finca Cortesin alcanzó SQL (CV: 55)", timestamp: "Hace 3 días", type: "sql" },
];

export const sparklineData = {
  traffic: [980, 1020, 1050, 1100, 1080, 1150, 1200, 1240],
  leads: [280, 295, 310, 320, 340, 355, 370, 387],
  mqls: [62, 68, 72, 75, 78, 82, 88, 94],
  sqls: [10, 11, 12, 13, 14, 15, 16, 18],
};

export const funnelData = [
  { stage: "Market Research", count: 847, color: "#6366F1" },
  { stage: "Enrichment", count: 383, rate: "45%", color: "#8B5CF6" },
  { stage: "Active Cadence", count: 183, rate: "48%", color: "#A78BFA" },
  { stage: "Nurturing", count: 68, rate: "37%", color: "#C4B5FD" },
  { stage: "SQL", count: 18, rate: "26%", color: "#10B981" },
];

export const analyticsData = {
  funnelConversion: [
    { stage: "Traffic \u2192 Lead", rate: 10.2, target: 12, color: "#F59E0B" },
    { stage: "Lead \u2192 MQL", rate: 11.8, target: 10, color: "#10B981" },
    { stage: "MQL \u2192 SQL", rate: 26.3, target: 25, color: "#10B981" },
    { stage: "SQL \u2192 Won", rate: 23.1, target: 30, color: "#EF4444" },
  ],
  cadencePerformance: [
    { name: "Spain Boutique 4-5★", rate: 18.3 },
    { name: "LATAM Independent", rate: 11.7 },
    { name: "Recycled Q4 2025", rate: 8.1 },
  ],
  channelEffectiveness: [
    { name: "Email", value: 12.3, color: "#6366F1" },
    { name: "LinkedIn", value: 31.4, color: "#3B82F6" },
    { name: "WhatsApp", value: 47.2, color: "#10B981" },
  ],
  contactValueDistribution: [
    { range: "0-10", count: 245 },
    { range: "10-20", count: 198 },
    { range: "20-30", count: 156 },
    { range: "30-40", count: 112 },
    { range: "40-50", count: 78 },
    { range: "50+", count: 58 },
  ],
  weeklySQLs: [
    { week: "W1", sqls: 3, target: 10 },
    { week: "W2", sqls: 5, target: 10 },
    { week: "W3", sqls: 7, target: 10 },
    { week: "W4", sqls: 4, target: 10 },
    { week: "W5", sqls: 6, target: 10 },
    { week: "W6", sqls: 9, target: 10 },
    { week: "W7", sqls: 8, target: 10 },
    { week: "W8", sqls: 8, target: 10 },
  ],
  kpiTable: [
    { category: "Básicos", metric: "Tráfico Web", current: "1,240", target: "1,500", trend: "+8%", status: "warning" },
    { category: "Básicos", metric: "Leads Generados", current: "387", target: "350", trend: "+31%", status: "success" },
    { category: "Básicos", metric: "MQLs", current: "94", target: "80", trend: "+24%", status: "success" },
    { category: "Básicos", metric: "SQLs", current: "18", target: "20", trend: "+19%", status: "warning" },
    { category: "Conversión", metric: "Traffic \u2192 Lead", current: "10.2%", target: "12%", trend: "-1.2%", status: "danger" },
    { category: "Conversión", metric: "Lead \u2192 MQL", current: "11.8%", target: "10%", trend: "+2.3%", status: "success" },
    { category: "Conversión", metric: "MQL \u2192 SQL", current: "26.3%", target: "25%", trend: "+1.8%", status: "success" },
    { category: "Conversión", metric: "SQL \u2192 Won", current: "23.1%", target: "30%", trend: "-2.4%", status: "danger" },
    { category: "Actividad SDR", metric: "Emails Enviados/Día", current: "45", target: "50", trend: "+5", status: "warning" },
    { category: "Actividad SDR", metric: "LinkedIn Enviados/Día", current: "12", target: "15", trend: "+2", status: "warning" },
    { category: "Actividad SDR", metric: "Tasa de Respuesta", current: "14.2%", target: "15%", trend: "+1.1%", status: "warning" },
    { category: "Actividad SDR", metric: "Tiempo Medio Respuesta", current: "2.4h", target: "2h", trend: "-0.3h", status: "warning" },
  ],
};
